In [2]:
import pandas as pd
df=pd.read_csv("STUDENT.csv")
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72.0,74
1,female,group C,some college,standard,completed,69,90.0,88
2,female,group B,master's degree,standard,none,90,95.0,93
3,male,group A,associate's degree,free/reduced,none,47,NaN,44
4,male,group C,some college,standard,none,76,78.0,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99.0,95
996,male,group C,high school,free/reduced,none,62,55.0,55
997,female,group C,high school,free/reduced,completed,59,71.0,65
998,female,group D,some college,standard,completed,68,78.0,77
999,female,group D,some college,free/reduced,none,77,86.0,86

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   object
 1   race/ethnicity               1000 non-null   object
 2   parental level of education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test preparation course      1000 non-null   object
 5   math score                   1000 non-null   int64
 6   reading score                981 non-null    float64
 7   writing score                1000 non-null   int64
dtypes: float64(1), int64(2), object(5)
memory usage: 43.0+ KB

In [4]:
df.describe()

       math score  reading score  writing score
count  1000.00000     981.000000    1000.000000
mean     66.08900      69.163099      68.054000
std      15.16308      14.588222      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

In [6]:
meanvalue=df["math score"].mean()
print("Mean:",meanvalue)

Mean: 66.089

In [7]:
medianvalue=df["math score"].median()
print("Median:",medianvalue)

Median: 66.0

In [8]:
modevalue=df["math score"].mode()[0]
print("Mode:",modevalue)

Mode: 65

In [9]:
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72.0,74
1,female,group C,some college,standard,completed,69,90.0,88
2,female,group B,master's degree,standard,none,90,95.0,93
3,male,group A,associate's degree,free/reduced,none,47,NaN,44
4,male,group C,some college,standard,none,76,78.0,75

In [10]:
df.head(3)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72.0,74
1,female,group C,some college,standard,completed,69,90.0,88
2,female,group B,master's degree,standard,none,90,95.0,93

In [11]:
df.tail()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
995,female,group E,master's degree,standard,completed,88,99.0,95
996,male,group C,high school,free/reduced,none,62,55.0,55
997,female,group C,high school,free/reduced,completed,59,71.0,65
998,female,group D,some college,standard,completed,68,78.0,77
999,female,group D,some college,free/reduced,none,77,86.0,86

In [12]:
df.isnull()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,True,False
4,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...
995,False,False,False,False,False,False,False,False
996,False,False,False,False,False,False,False,False
997,False,False,False,False,False,False,False,False
998,False,False,False,False,False,False,False,False
999,False,False,False,False,False,False,False,False

In [13]:
df.isnull().sum()

gender                          0
race/ethnicity                  0
parental level of education     0
lunch                           0
test preparation course         0
math score                      0
reading score                  19
writing score                   0
dtype: int64

In [14]:
df.head(2)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72.0,74
1,female,group C,some college,standard,completed,69,90.0,88

In [15]:
import numpy as n
df["reading score"].replace("",n.nan,inplace=True)

<ipython-input-15-815255d99ba3>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["reading score"].replace("",n.nan,inplace=True)

In [16]:
df.isnull().sum()

gender                          0
race/ethnicity                  0
parental level of education     0
lunch                           0
test preparation course         0
math score                      0
reading score                  19
writing score                   0
dtype: int64

In [17]:
df.replace("",n.nan,inplace=True)

In [18]:
df.isnull().sum()

gender                          0
race/ethnicity                  0
parental level of education     0
lunch                           0
test preparation course         0
math score                      0
reading score                  19
writing score                   0
dtype: int64

In [21]:
df["writing score"]=pd.to_numeric(df["writing score"],errors="coerce")

df["writing score"].fillna(df["writing score"].mean(),inplace=True)

<ipython-input-21-da442033a3f3>:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["writing score"].fillna(df["writing score"].mean(),inplace=True)

In [24]:
df["writing score"]

0      74
1      88
2      93
3      44
4      75
       ..
995    95
996    55
997    65
998    77
999    86
Name: writing score, Length: 1000, dtype: int64

In [25]:
df["writing score"].fillna(df["writing score"].median(),inplace=True)

In [26]:
df["writing score"]

0      74
1      88
2      93
3      44
4      75
       ..
995    95
996    55
997    65
998    77
999    86
Name: writing score, Length: 1000, dtype: int64

In [ ]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df["lunch-encoded"]=le.fit_transform(df["lunch"])
df["lunch-encoded"],df["lunch"]